#!/usr/bin/env python3
"""
Split large intro.md files into chunks of max 50KB for translation.

Usage:
    python3 split_for_translation.py                # Split all intro.md files in en/docs/
    python3 split_for_translation.py --dry-run       # Show what would be done
    python3 split_for_translation.py --max-size 30   # Use 30KB max instead of 50KB

Files ≤ max-size remain untouched (agents translate intro.md directly).
Files > max-size are split into intro_part1.md, intro_part2.md, etc.

After translation, use reassemble_translations.py to merge chunks back.
"""

import os
import re
import sys
from pathlib import Path

MAX_CHUNK_SIZE = 50 * 1024  # 50 KB


def split_file(filepath, max_size=MAX_CHUNK_SIZE, dry_run=False):
    """
    Split a file into chunks of max max_size bytes.
    Splits at blank lines for clean boundaries.
    Returns (num_chunks, total_bytes) or (0, file_bytes) if no split needed.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()  # preserves \n at end of each line

    total_bytes = sum(len(line.encode('utf-8')) for line in lines)

    if total_bytes <= max_size:
        return 0, total_bytes  # No split needed

    chunks = []
    current_chunk = []
    current_size = 0

    for line in lines:
        line_size = len(line.encode('utf-8'))

        if current_size + line_size > max_size and current_chunk:
            # Over limit — find best split point
            # Look back for a blank line (paragraph/section boundary)
            split_idx = len(current_chunk)
            for j in range(len(current_chunk) - 1, max(0, len(current_chunk) - 300), -1):
                if current_chunk[j].strip() == '':
                    split_idx = j + 1
                    break

            # Save chunk up to split point
            chunks.append(''.join(current_chunk[:split_idx]))

            # Carry over remaining lines + current line
            remaining = current_chunk[split_idx:]
            current_chunk = remaining + [line]
            current_size = sum(len(l.encode('utf-8')) for l in current_chunk)
        else:
            current_chunk.append(line)
            current_size += line_size

    # Last chunk
    if current_chunk:
        chunks.append(''.join(current_chunk))

    if not dry_run:
        parent = filepath.parent
        for i, chunk in enumerate(chunks, 1):
            chunk_path = parent / f'intro_part{i}.md'
            with open(chunk_path, 'w', encoding='utf-8') as f:
                f.write(chunk)

    return len(chunks), total_bytes


def main():
    dry_run = '--dry-run' in sys.argv
    max_size = MAX_CHUNK_SIZE

    # Parse --max-size
    for i, arg in enumerate(sys.argv):
        if arg == '--max-size' and i + 1 < len(sys.argv):
            max_size = int(sys.argv[i + 1]) * 1024

    base_dir = Path('en/docs')

    if not base_dir.exists():
        print(f"❌ Directory {base_dir} not found. Run from project root.")
        sys.exit(1)

    # Check for existing chunks (prevent double-splitting)
    existing_chunks = list(base_dir.rglob('intro_part*.md'))
    if existing_chunks:
        print(f"⚠️  Found {len(existing_chunks)} existing intro_part*.md files!")
        print(f"   Run reassemble_translations.py first, or delete them manually.")
        print(f"   First few: {[str(p) for p in existing_chunks[:3]]}")
        sys.exit(1)

    all_files = sorted(base_dir.rglob('intro.md'))
    total_files = len(all_files)
    split_count = 0
    no_split_count = 0
    total_chunks = 0
    translation_files = []

    print(f"{'DRY RUN - ' if dry_run else ''}Scanning {total_files} intro.md files (max chunk size: {max_size // 1024}KB)\n")

    for filepath in all_files:
        rel = filepath.relative_to(Path('.'))
        num_chunks, file_bytes = split_file(filepath, max_size=max_size, dry_run=dry_run)

        if num_chunks == 0:
            no_split_count += 1
            total_chunks += 1
            translation_files.append((str(rel), file_bytes, 1, 1))
            # Small file — no indicator needed
        else:
            split_count += 1
            total_chunks += num_chunks
            for i in range(1, num_chunks + 1):
                chunk_path = filepath.parent / f'intro_part{i}.md'
                chunk_rel = chunk_path.relative_to(Path('.'))
                translation_files.append((str(chunk_rel), None, i, num_chunks))
            print(f"  {'Would split' if dry_run else 'Split'}: {rel} ({file_bytes:,} bytes) → {num_chunks} parts")

    print(f"\n{'=' * 60}")
    print(f"Files scanned:     {total_files}")
    print(f"No split needed:   {no_split_count} (≤ {max_size // 1024}KB)")
    print(f"Split:             {split_count}")
    print(f"Total chunks/files to translate: {total_chunks}")
    print(f"{'=' * 60}")

    # Write task list
    task_file = Path('TRANSLATION_FILES.md')
    with open(task_file, 'w', encoding='utf-8') as f:
        f.write("# Translation Files\n\n")
        f.write(f"Generated by `split_for_translation.py`. Total: **{total_chunks} files** to translate.\n\n")
        f.write("## Agent-Prompt (kopieren und anpassen)\n\n")
        f.write("```\n")
        f.write("Übersetze alle deutschen Texte in der Datei `<DATEIPFAD>` ins Englische.\n")
        f.write("Übersetze auch deutschsprachige Kommentare in Codebeispielen.\n")
        f.write("Lass Code, Links, Dateipfade und Markdown-Formatierung unverändert.\n")
        f.write("Übersetze Frontmatter-Felder (title:) ebenfalls.\n")
        f.write("```\n\n")
        f.write("## Alle Dateien\n\n")

        current_chapter = None
        file_num = 0
        for fpath, fsize, part_num, total_parts in translation_files:
            # Extract chapter
            parts = Path(fpath).parts
            chapter = parts[2] if len(parts) > 2 else '?'
            if chapter != current_chapter:
                current_chapter = chapter
                f.write(f"\n### {chapter}\n\n")

            file_num += 1
            if total_parts == 1:
                size_str = f" ({fsize:,} bytes)" if fsize else ""
                f.write(f"{file_num}. `{fpath}`{size_str}\n")
            else:
                f.write(f"{file_num}. `{fpath}` (part {part_num}/{total_parts})\n")

    print(f"\n📝 Task list written to {task_file}")

    if dry_run:
        print("\n⚡ Run without --dry-run to actually split the files.")


if __name__ == '__main__':
    main()
